# Generated by Django 5.1 on 2026-08-30 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_penalty_suspension_appeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessonboardstatus',
            name='needs_manual_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='driververification',
            name='verification_type',
            field=models.CharField(choices=[('nin', 'NIN'), ('bvn', 'BVN'), ('face_match', 'Face Match'), ('bank_account', 'Bank Account')], max_length=20),
        ),
        migrations.CreateModel(
            name='BusinessVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('tin', 'TIN'), ('rc', 'RC/CAC Number'), ('bvn', 'BVN')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('provider_name', models.CharField(blank=True, max_length=60)),
                ('provider_ref', models.CharField(blank=True, max_length=120)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='accounts.business')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('business', 'verification_type'), name='uniq_business_verification_type')],
            },
        ),
    ]
