# Generated by Django 5.1 on 2026-08-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_businessonboardstatus_needs_manual_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessonboardstatus',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
