# Generated by Django 5.1 on 2026-08-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0028_globaltag_taggroup_menucategory_global_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggroup',
            name='images',
            field=models.ImageField(upload_to='categories/images/'),
        ),
    ]
